---
title: 'Data-based, synthesis-driven: setting the agenda for computational ecology'
short: The role of computational ecology
keyword:
  - computational ecology
  - ecological synthesis
  - data sharing
date: 2017-03-02T00:00:00.000Z
abstract: >
  Computational thinking is the integration of algorithms, software, and data,
  to

  solve general questions in a field. Computation ecology has the potential to

  transform the way ecologists think about the integration of data and models.
  As

  the practice is gaining prominence as a way to conduct ecological research, it

  is important to reflect on what its agenda could be, and how it fits within
  the

  broader landscape of ecological research. In this contribution, we suggest
  areas

  in which empirical ecologists, modellers, and the emerging community of

  computational ecologists could engage in a constructive dialogue to build on
  one

  another's expertise; specifically, about the need to make predictions from

  models actionable, about the best standards to represent ecological data, and

  about the proper ways to credit data collection and data reuse. We discuss how

  training can be amended to improve computational literacy.
author:
  - family: Poisot
    given: Timothée
    affiliations:
      - 1
      - 2
      - 3
    email: timothee.poisot@umontreal.ca
    id: tp
    orcid: 0000-0002-0735-5184
  - family: LaBrie
    given: Richard
    affiliations:
      - 1
      - 2
  - family: Larson
    given: Erin
    affiliations:
      - 4
  - family: Rahlin
    given: Anastasia
    affiliations:
      - 5
affiliation:
  - id: 1
    text: 'Université de Montréal, Département de Sciences Biologiques'
  - id: 2
    text: >-
      Groupe de Recherche Interuniversitaire en Limnologie et environnement
      aquatique
  - id: 3
    text: Québec Centre for Biodiversity Sciences
  - id: 4
    text: 'Department of Ecology and Evolutionary Biology, Cornell University'
  - id: 5
    text: Illinois Natural History Survey
cleveref: true
...
